### PR TITLE
Fix the URL parameters for querying prices for given connectionIds

### PR DESCRIPTION
**Pull request by qinwenshi**
Hi there, I'm testing this repository and it turns out that when calling the prices API, it no long accept the connectionIds in the query string like this: 
```
https://tickets.oebb.at/api/offer/v1/prices?connectionIds=d5a3f2c68a85be4cb3c16be01186ee093873fb48be01b8c0e732d2021fc56f3b,785b73dfe8c85ee44509a38e21afab5ecb92f5c497e5205342bf31435e7a48d3,5fbfe048f5d486b8be0ecf839664dfa7170c9002d0
```

but this works

```
https://tickets.oebb.at/api/offer/v1/prices?connectionIds[]=d5a3f2c68a85be4cb3c16be01186ee093873fb48be01b8c0e732d2021fc56f3b&connectionIds[]=785b73dfe8c85ee44509a38e21afab5ecb92f5c497e5205342bf31435e7a48d3&connectionIds[]=5fbfe048f5d486b8be0ecf839664dfa7170c9002d0
```

### CODE REVIEW

**Comment by juliuste** [comment]
Thank you very much for your contribution! Will review ~later today~ ~this weekend~ after christmas (sorry about the delay) 🙂

**Comment by qinwenshi** [comment]
Thanks for the reply, currently only my first two commits follows your original API interface, the rest changes are only for my own usage, and you might not need it.

[da2da5c](https://github.com/juliuste/oebb/pull/11/commits/da2da5cdaefac2a3d02bab38060e505aee45e0f9)

[5e69896](https://github.com/juliuste/oebb/pull/11/commits/5e698968ef60ff9672c9cc8aa86b87118e990d85)

**Comment by juliuste** [comment]
*Cough* I finally had time to fix the library, but I had completely forgotten about your PR. If you have the time, feel free to check out the current status of master (which works again, finally), and tell me if you miss any information.

Again - Thank you very very much for the efforts, I'm really sorry that I totally forgot about your contribution here 🤦‍♂

**Comment by juliuste** [comment]
Please re-open if you're still interested in merging some feature / support for some field that I left out in the general re-write.

**Pull request closed without merging**
